const GEAR_SET = {
         "gearset1":{
            "id":"gearset1",
            "name":"Azure Dragon",
            "description":"",
            "effect":[{
               "type":"add_dodge_reduction",
               "duration":0,
               "amount":4,
               "chance":100
            }],
            "member_list":["acsy33","wpn1277","wpn1278"],
            "hash":"45f5504acb75907998533944a7f6eb375cca5f84"
         },
         "gearset2":{
            "id":"gearset2",
            "name":"Vermilion Bird Set",
            "description":"",
            "effect":[{
               "type":"attacker_damage_bonus",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["acsy34","wpn1279","wpn1280"],
            "hash":"926951db7e969e93255543b5c676c9c65efe238e"
         },
         "gearset3":{
            "id":"gearset3",
            "name":"White Tiger Set",
            "description":"",
            "effect":[{
               "type":"add_critical_chance",
               "duration":0,
               "amount":8,
               "chance":100
            }],
            "member_list":["acsy35","wpn1281","wpn1282"],
            "hash":"d1ef1d8c6300693d5334e0f7760d8935c2979295"
         },
         "gearset4":{
            "id":"gearset4",
            "name":"Black Turtle Set",
            "description":"",
            "effect":[{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["acsy36","wpn1283","wpn1284"],
            "hash":"a0382fdc81ef9be3191b895e23253e7d41064a52"
         },
         "gearset5":{
            "id":"gearset5",
            "name":"Kirin Set",
            "description":"",
            "effect":[{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":4,
               "chance":100
            }],
            "member_list":["acsy37","wpn1285","wpn1286","wpn1287","wpn1350"],
            "hash":"236826f5e5839082a11894c0cd2d94182b59fc84"
         },
         "gearset6":{
            "id":"gearset6",
            "name":"Holy Beast Hunter Set",
            "description":"",
            "effect":[{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"absorb_attacker_hp_present",
               "duration":0,
               "amount":2,
               "chance":10
            }],
            "member_list":["back569","hair645","hair646","set2122","set2123","wpn1288"],
            "hash":"e01daa16ac569524c0606e3402590ac0dfcffc5a"
         },
         "gearset7":{
            "id":"gearset7",
            "name":"7th Anniversary Set",
            "description":"",
            "effect":[{
               "type":"xp_bouns",
               "duration":0,
               "amount":1000,
               "chance":0
            }],
            "member_list":["hair643","hair644","set2120","set2121"],
            "hash":"f89f196058a117c134b9f55a5e76411cf076ff8d"
         },
         "gearset8":{
            "id":"gearset8",
            "name":"Zen Monk Set",
            "description":"",
            "effect":[{
               "type":"add_purify_chance",
               "duration":0,
               "amount":3,
               "chance":100
            }],
            "member_list":["hair647","hair648","set2124","set2125"],
            "hash":"7ff9b00abaa33429e44fa40c8d22298e193e9081"
         },
         "gearset9":{
            "id":"gearset9",
            "name":"Martial Monk Set",
            "description":"",
            "effect":[{
               "type":"effect_agility",
               "duration":0,
               "amount":1,
               "chance":100
            }],
            "member_list":["hair649","hair650","set2126","set2127"],
            "hash":"055f4e284847429f68108374e7007b115fa10f6c"
         },
         "gearset10":{
            "id":"gearset10",
            "name":"Crew S8 Set",
            "description":"",
            "effect":[{
               "type":"add_dodge_reduction",
               "duration":0,
               "amount":7,
               "chance":100
            }],
            "member_list":["back603","back604","wpn1331","wpn1332","wpn1333","wpn1334","wpn1335"],
            "hash":"6647e5d03eb1121afc83974cc9d071380295c75a"
         },
         "gearset11":{
            "id":"gearset11",
            "name":"Chakra Ancestor Set",
            "description":"",
            "effect":[{
               "type":"effect_max_cp_present",
               "duration":1,
               "amount":5,
               "chance":100
            },{
               "type":"recieve_damage_cp",
               "duration":1,
               "amount":8,
               "chance":100
            },{
               "type":"add_cp_amount_present",
               "duration":1,
               "amount":3,
               "chance":100
            }],
            "member_list":["back605","hair677","hair678","set2216","set2217","wpn1341"],
            "hash":"5e5480e0fbccf1aa60f4aa20116de62a5c022bd6"
         },
         "gearset12":{
            "id":"gearset12",
            "name":"Crew S9 Set",
            "description":"",
            "effect":[{
               "type":"add_hp_amount_present",
               "duration":1,
               "amount":4,
               "chance":100
            }],
            "member_list":["back608","back609","wpn1345","wpn1346","wpn1347","wpn1348","wpn1349"],
            "hash":"6d18c7f69c225d955b41393fa7c581bd9209aff3"
         },
         "gearset13":{
            "id":"gearset13",
            "name":"Crew S10 Set",
            "description":"",
            "effect":[{
               "type":"effect_agility",
               "duration":0,
               "amount":1,
               "chance":100
            }],
            "member_list":["back611","back612","wpn1357","wpn1358","wpn1359","wpn1360","wpn1361"],
            "hash":"a9eae7f2b1f163f588a3a05971d59ae773b98fd4"
         },
         "gearset14":{
            "id":"gearset14",
            "name":"Crew S11 Set",
            "description":"",
            "effect":[{
               "type":"add_hp_amount",
               "duration":0,
               "amount":175,
               "chance":100
            }],
            "member_list":["back615","back616","wpn1364","wpn1365","wpn1366","wpn1367","wpn1368"],
            "hash":"f15b3286228196ef308f3904456e525a214afc2b"
         },
         "gearset15":{
            "id":"gearset15",
            "name":"test",
            "description":"",
            "effect":[{
               "type":"reduce_damage_bonus",
               "duration":0,
               "amount":150,
               "chance":100
            }],
            "member_list":["back4","wpn1"],
            "hash":"fef88d6db26a02ed3ac02f265397f761a43025b2"
         },
         "gearset16":{
            "id":"gearset16",
            "name":"Crew S12 Set",
            "description":"",
            "effect":[{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":8,
               "chance":100
            }],
            "member_list":["back620","back621","wpn1373","wpn1374","wpn1375","wpn1376","wpn1377"],
            "hash":"8218d9ce954082a6e236e62aab595236e770354f"
         },
         "gearset17":{
            "id":"gearset17",
            "name":"Armor Ninja Set",
            "description":"",
            "effect":[{
               "type":"attacker_damage_bonus",
               "duration":0,
               "amount":8,
               "chance":100
            }],
            "member_list":["hair697","hair698","set2270","set2271"],
            "hash":"40b3f708e01629bdaab7aedb4d878b10f2c8cebd"
         },
         "gearset18":{
            "id":"gearset18",
            "name":"Mech Ninja Set",
            "description":"",
            "effect":[{
               "type":"reduce_damage_bonus",
               "duration":0,
               "amount":150,
               "chance":100
            }],
            "member_list":["hair699","hair700","set2272","set2273"],
            "hash":"4c6bca159ca60236fb362aa6596004559bb9b1c2"
         },
         "gearset19":{
            "id":"gearset19",
            "name":"Crew S13 Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":5,
               "chance":100
            }],
            "member_list":["back627","back629","wpn1386","wpn1390","wpn1391","wpn1392","wpn1393"],
            "hash":"8c95aad6297b475cc870927b0b136b22db32e057"
         },
         "gearset20":{
            "id":"gearset20",
            "name":"Crew S14 Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":8,
               "chance":100
            }],
            "member_list":["back630","back631","wpn1394","wpn1395","wpn1396","wpn1397","wpn1398"],
            "hash":"0adf5a2e5d53d4ff5535e8c6e02f56f4ac9190a1"
         },
         "gearset21":{
            "id":"gearset21",
            "name":"Crew S15 Set",
            "description":"",
            "effect":[{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":8,
               "chance":100
            }],
            "member_list":["back636","back637","wpn1401","wpn1402","wpn1403","wpn1404","wpn1405"],
            "hash":"51850968b6b08775cd33408d65331bc35a1ea6ed"
         },
         "gearset22":{
            "id":"gearset22",
            "name":"Crew S16 Set",
            "description":"",
            "effect":[{
               "type":"attacker_damage_bonus",
               "duration":0,
               "amount":10,
               "chance":100
            }],
            "member_list":["back643","back644","wpn1419","wpn1420","wpn1421","wpn1422","wpn1423"],
            "hash":"b313726d13b92223c3b3f6d66b74757354f6b764"
         },
         "gearset23":{
            "id":"gearset23",
            "name":"Crew S17 Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount",
               "duration":0,
               "amount":150,
               "chance":100
            }],
            "member_list":["back646","back647","wpn1427","wpn1428","wpn1429","wpn1430","wpn1431"],
            "hash":"177345c5f63650a1f304f351b439b588256aa8f6"
         },
         "gearset24":{
            "id":"gearset24",
            "name":"Crew S18 Set",
            "description":"",
            "effect":[{
               "type":"effect_max_cp_present",
               "duration":0,
               "amount":15,
               "chance":100
            }],
            "member_list":["back658","back659","wpn1442","wpn1443","wpn1444","wpn1445","wpn1446"],
            "hash":"6e6a7fae6b21a0e05e9c6dd0ab072c753d72a5e7"
         },
         "gearset25":{
            "id":"gearset25",
            "name":"Crew S19 Set",
            "description":"",
            "effect":[{
               "type":"add_critical_chance",
               "duration":0,
               "amount":10,
               "chance":100
            }],
            "member_list":["back663","back664","wpn1450","wpn1451","wpn1452","wpn1453","wpn1454"],
            "hash":"958bdbcb6a1e0b30bc65a4381c2fc88b01bef151"
         },
         "gearset26":{
            "id":"gearset26",
            "name":"Evil Spirit Set",
            "description":"",
            "effect":[{
               "type":"add_hp_amount",
               "duration":0,
               "amount":100,
               "chance":100
            },{
               "type":"add_hp_amount",
               "duration":0,
               "amount":150,
               "chance":100
            },{
               "type":"add_hp_amount_present",
               "duration":10,
               "amount":10,
               "chance":100
            }],
            "member_list":["back623","hair691","hair692","set2264","set2265","wpn1379"],
            "hash":"c4a382b39f56ed8250e5817fea4c4b939a6da783"
         },
         "gearset27":{
            "id":"gearset27",
            "name":"Crew S20 Set",
            "description":"",
            "effect":[{
               "type":"absorb_attacker_hp_present",
               "duration":0,
               "amount":5,
               "chance":8
            }],
            "member_list":["back665","back666","wpn1455","wpn1456","wpn1457","wpn1458","wpn1459"],
            "hash":"68026934494c4505f2483acfb41c007bbb635d4e"
         },
         "gearset28":{
            "id":"gearset28",
            "name":"Fire Ninja Elite Set",
            "description":"Fire Ninja Elite Set",
            "effect":[{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":5,
               "chance":100
            },{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":10,
               "chance":100
            }],
            "member_list":["back674","hair735","hair736","set2390","set2391","wpn1480","wpn1487"],
            "hash":"f8e4377eeb66db6bba1299325602a7425157228f"
         },
         "gearset29":{
            "id":"gearset29",
            "name":"Water Ninja Elite Set",
            "description":"Water Ninja Elite Set",
            "effect":[{
               "type":"add_purify_chance",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"add_purify_chance",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"add_purify_chance",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["back675","hair737","hair738","set2392","set2393","wpn1481","wpn1488"],
            "hash":"31ecd9322362d20f74bbe19220c873c9340b9d07"
         },
         "gearset30":{
            "id":"gearset30",
            "name":"Wind Ninja Elite Set",
            "description":"Wind Ninja Elite Set",
            "effect":[{
               "type":"add_dodge_random",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"add_dodge_random",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"add_dodge_random",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["back676","hair739","hair740","set2394","set2395","wpn1482","wpn1489"],
            "hash":"db078d1ab30b8426afca2f6ed5d30435171f0680"
         },
         "gearset31":{
            "id":"gearset31",
            "name":"Lightning Ninja Elite Set",
            "description":"Lightning Ninja Elite Set",
            "effect":[{
               "type":"add_critical_chance",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"add_critical_chance",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"add_critical_chance",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["back677","hair741","hair742","set2396","set2397","wpn1483","wpn1490"],
            "hash":"17652d01c0f5900a1d11235539480e458e4ee167"
         },
         "gearset32":{
            "id":"gearset32",
            "name":"Earth Ninja Elite Set",
            "description":"Earth Ninja Elite Set",
            "effect":[{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["back678","hair743","hair744","set2398","set2399","wpn1484","wpn1491"],
            "hash":"5dd9957742bc25b185629e6361966e5b997be243"
         },
         "gearset33":{
            "id":"gearset33",
            "name":"Crew S21 Set",
            "description":"",
            "effect":[{
               "type":"add_dodge_reduction",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["back672","back673","wpn1470","wpn1471","wpn1472","wpn1473","wpn1474"],
            "hash":"99e843815466e21596da757f58d4f7a237dbcf11"
         },
         "gearset34":{
            "id":"gearset34",
            "name":"Crew S22 Set",
            "description":"",
            "effect":[{
               "type":"reduce_damage_bonus",
               "duration":0,
               "amount":150,
               "chance":100
            }],
            "member_list":["back681","back682","wpn1493","wpn1494","wpn1495","wpn1496","wpn1497"],
            "hash":"567357f6daafb795ef06e5ffb163efe352f17034"
         },
         "gearset35":{
            "id":"gearset35",
            "name":"Night Tengu Set",
            "description":"",
            "effect":[{
               "type":"absorb_attacker_hp_present",
               "duration":0,
               "amount":1,
               "chance":5
            },{
               "type":"absorb_attacker_hp_present",
               "duration":0,
               "amount":1,
               "chance":5
            },{
               "type":"absorb_attacker_hp_present",
               "duration":0,
               "amount":2,
               "chance":15
            }],
            "member_list":["back684","hair757","hair758","set2416","set2417","wpn1498"],
            "hash":"f8617bf4a35b0c00487f0d3f8fb1abb79165bc98"
         },
         "gearset36":{
            "id":"gearset36",
            "name":"High Tech Set",
            "description":"",
            "effect":[{
               "type":"reduce_damage_bonus",
               "duration":0,
               "amount":50,
               "chance":100
            },{
               "type":"reduce_damage_bonus",
               "duration":0,
               "amount":50,
               "chance":100
            },{
               "type":"reduce_damage_bonus",
               "duration":0,
               "amount":150,
               "chance":100
            }],
            "member_list":["back685","hair759","hair760","set2418","set2419","wpn1499"],
            "hash":"659755fb7aa08371bd090f4dc811ef7632d564cb"
         },
         "gearset37":{
            "id":"gearset37",
            "name":"Conjurer Set",
            "description":"",
            "effect":[{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":5,
               "chance":100
            },{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":5,
               "chance":100
            },{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":10,
               "chance":100
            }],
            "member_list":["back686","hair761","hair762","set2420","set2421","wpn1500"],
            "hash":"fb178ec5821ea6598ceb28c732c8036386ea387c"
         },
         "gearset38":{
            "id":"gearset38",
            "name":"Saint Knight Set",
            "description":"",
            "effect":[{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":1,
               "chance":100
            },{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":1,
               "chance":100
            },{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":4,
               "chance":100
            }],
            "member_list":["back687","hair763","hair764","set2422","set2423","wpn1501"],
            "hash":"6dd225219c7a6f42c913dac6d1e9c7635dc17261"
         },
         "gearset39":{
            "id":"gearset39",
            "name":"Magic Emissary Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":1,
               "chance":100
            },{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["back688","hair765","hair766","set2424","set2425","wpn1502"],
            "hash":"9879df00cbb60f78f8fd7857393355c02c42485b"
         },
         "gearset40":{
            "id":"gearset40",
            "name":"Cyborg Set",
            "description":"",
            "effect":[{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":20,
               "chance":100
            },{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":20,
               "chance":100
            },{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":100,
               "chance":100
            }],
            "member_list":["back689","hair767","hair768","set2426","set2427","wpn1503"],
            "hash":"f4c79f2885e9e1f8ce47e12fb587c660c633f7ff"
         },
         "gearset41":{
            "id":"gearset41",
            "name":"8th Anniversary Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"xp_bouns",
               "duration":0,
               "amount":3000,
               "chance":100
            },{
               "type":"add_purify_chance",
               "duration":0,
               "amount":3,
               "chance":100
            }],
            "member_list":["acsy50","back692","hair755","hair756","set2406","set2407","wpn1492"],
            "hash":"79d21437cf3bde0d727556c5c869475808c464ac"
         },
         "gearset42":{
            "id":"gearset42",
            "name":"True 8th Anniversary Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"xp_bouns",
               "duration":0,
               "amount":10000,
               "chance":100
            },{
               "type":"add_purify_chance",
               "duration":0,
               "amount":12,
               "chance":100
            }],
            "member_list":["acsy51","back693","hair769","hair770","set2428","set2429","wpn1509"],
            "hash":"891ffe8ae6551e47eea7df6a7efe70523945c678"
         },
         "gearset43":{
            "id":"gearset43",
            "name":"Crew S23 Set",
            "description":"",
            "effect":[{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":150,
               "chance":100
            }],
            "member_list":["back690","back691","wpn1504","wpn1505","wpn1506","wpn1507","wpn1508"],
            "hash":"c8544f6d3608411b718fc117969eb967464e25b5"
         },
         "gearset44":{
            "id":"gearset44",
            "name":"Crew S24 Set",
            "description":"",
            "effect":[{
               "type":"attacker_critical_damage_bonus",
               "duration":0,
               "amount":12,
               "chance":100
            }],
            "member_list":["back695","back696","wpn1515","wpn1516","wpn1517","wpn1518","wpn1519"],
            "hash":"f59121dffcb64842f25942eec118c894bc0ac644"
         },
         "gearset45":{
            "id":"gearset45",
            "name":"Christmas Kyubi Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":5,
               "chance":100
            },{
               "type":"add_purify_chance",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"add_purify_chance",
               "duration":0,
               "amount":3,
               "chance":100
            }],
            "member_list":["back704","hair775","hair776","set2458","set2459","wpn1533"],
            "hash":"d2d75021e2c6e7b10410a9f48df2aeb9ea963739"
         },
         "gearset46":{
            "id":"gearset46",
            "name":"Crew S25 Set",
            "description":"",
            "effect":[{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":8,
               "chance":100
            }],
            "member_list":["back697","back698","wpn1520","wpn1521","wpn1522","wpn1523","wpn1524"],
            "hash":"17643ebe529742a39f7895c04262fc9a25d4d110"
         },
         "gearset47":{
            "id":"gearset47",
            "name":"Christmas Hachibi Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":5,
               "chance":100
            },{
               "type":"attacker_critical_damage_bonus",
               "duration":0,
               "amount":10,
               "chance":100
            },{
               "type":"attacker_critical_damage_bonus",
               "duration":0,
               "amount":10,
               "chance":100
            }],
            "member_list":["back707","hair777","hair778","set2462","set2463","wpn1539"],
            "hash":"0f6898e10c10c7b9c77d945671ded425728560b8"
         },
         "gearset48":{
            "id":"gearset48",
            "name":"Christmas Nanabi Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":5,
               "chance":100
            },{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":10,
               "chance":100
            },{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":10,
               "chance":100
            }],
            "member_list":["back708","hair779","hair780","set2464","set2465","wpn1540"],
            "hash":"ea3014b808a44f22d80fb8c6f1338faf4b1ca72b"
         },
         "gearset49":{
            "id":"gearset49",
            "name":"Kagero Set",
            "description":"",
            "effect":[{
               "type":"add_sp_amount_present",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"add_sp_amount_present",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"add_sp_amount_present",
               "duration":0,
               "amount":5,
               "chance":100
            }],
            "member_list":["back712","hair784","hair785","set2484","set2485","wpn1548"],
            "hash":"0eee2d5d20c67eed7d50cc0813a7bf0be5f22871"
         },
         "gearset50":{
            "id":"gearset50",
            "name":"Crew S26 Set",
            "description":"",
            "effect":[{
               "type":"add_purify_chance",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["back705","back706","wpn1534","wpn1535","wpn1536","wpn1537","wpn1538"],
            "hash":"cca66dd95c9bed550d1d7281b5a6a1918cb4a4bc"
         },
         "gearset51":{
            "id":"gearset51",
            "name":"Crew S28 Set",
            "description":"",
            "effect":[{
               "type":"effect_max_cp_present",
               "duration":0,
               "amount":11,
               "chance":100
            },{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":4,
               "chance":100
            }],
            "member_list":["acsy55","back716","back717","wpn1553","wpn1554","wpn1555","wpn1556"],
            "hash":"7ca81a111d08d0115eb3f1f9c4cdb122d15f77a4"
         },
         "gearset54":{
            "id":"gearset54",
            "name":"Crew S27 Set",
            "description":"",
            "effect":[{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"attacker_damage_bonus",
               "duration":0,
               "amount":10,
               "chance":100
            }],
            "member_list":["acsy54","back709","back710","wpn1543","wpn1544","wpn1545","wpn1546"],
            "hash":"c511a546c8d16a21ef951940bd2765cb96131308"
         },
         "gearset55":{
            "id":"gearset55",
            "name":"Easter Rokubi Set",
            "description":"",
            "effect":[{
               "type":"add_critical_chance",
               "duration":0,
               "amount":7,
               "chance":100
            },{
               "type":"add_critical_chance",
               "duration":0,
               "amount":10,
               "chance":100
            },{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":150,
               "chance":100
            }],
            "member_list":["back719","hair788","hair789","set2504","set2505","wpn1558"],
            "hash":"8f13751a1d1aa0878464e4b7c7db907425c5e51c"
         },
         "gearset56":{
            "id":"gearset56",
            "name":"Easter Gobi Set",
            "description":"",
            "effect":[{
               "type":"add_purify_chance",
               "duration":0,
               "amount":6,
               "chance":100
            },{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":8,
               "chance":100
            },{
               "type":"reduce_damage_bonus",
               "duration":0,
               "amount":175,
               "chance":100
            }],
            "member_list":["back720","hair790","hair791","set2506","set2507","wpn1559"],
            "hash":"680523961b1e25154b2985ee5963f3dd18f636a4"
         },
         "gearset57":{
            "id":"gearset57",
            "name":"Rabbit Festival Set",
            "description":"",
            "effect":[{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":2,
               "chance":100
            },{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":3,
               "chance":100
            }],
            "member_list":["acsy56","back721","hair792","hair793","set2508","set2509","wpn1560","wpn1561","wpn1562","wpn1568"],
            "hash":"aa3290d8a027be1e7223d0f240fddb201a52e388"
         },
         "gearset58":{
            "id":"gearset58",
            "name":"Crew S29 Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":7,
               "chance":100
            },{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":7,
               "chance":100
            }],
            "member_list":["acsy57","back722","back723","wpn1563","wpn1564","wpn1565","wpn1566"],
            "hash":"8e10ae3b6850b60291ff1446dbe81259bafa68a9"
         },
         "gearset59":{
            "id":"gearset59",
            "name":"Crew S30 Set",
            "description":"",
            "effect":[{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"reduce_hp_present",
               "duration":0,
               "amount":2,
               "chance":30
            }],
            "member_list":["acsy58","back727","back728","wpn1573","wpn1574","wpn1575","wpn1576"],
            "hash":"1570dfabd3b89ac8f0e2de52213fc8461a200d96"
         },
         "gearset60":{
            "id":"gearset60",
            "name":"2018 Soccer Fever Set",
            "description":"",
            "effect":[{
               "type":"add_dodge_reduction",
               "duration":0,
               "amount":50,
               "chance":100
            }],
            "member_list":["set2546","set2547","wpn1587"],
            "hash":"1024483b8f5e289b2e89952f6fbcb71983f00557"
         },
         "gearset61":{
            "id":"gearset61",
            "name":"Crew S31 Set",
            "description":"",
            "effect":[{
               "type":"add_dodge_random",
               "duration":0,
               "amount":5,
               "chance":100
            },{
               "type":"absorb_attacker_hp_present",
               "duration":0,
               "amount":2,
               "chance":13
            }],
            "member_list":["acsy59","back729","back730","wpn1583","wpn1584","wpn1585","wpn1586"],
            "hash":"9354177eefca10b676c76cb91895ed92fd8cbde6"
         },
         "gearset62":{
            "id":"gearset62",
            "name":"Refined Chakra Set",
            "description":"Refined Chakra Set",
            "effect":[{
               "type":"add_dodge_random",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"add_critical_chance",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":3,
               "chance":100
            }],
            "member_list":["acsy44","back638","hair794","hair795","set2566","set2567","wpn1406"],
            "hash":"3b23b2ee89b902efefd589b4a0ad05bcf45d33e9"
         },
         "gearset63":{
            "id":"gearset63",
            "name":"Warrior Anton Set",
            "description":"Warrior Anton Set",
            "effect":[{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":2,
               "chance":100
            }],
            "member_list":["hair808","hair809","set2570","set2571"],
            "hash":"d6bd843838c04e39f4c5de9fac8c80062a5909bd"
         },
         "gearset64":{
            "id":"gearset64",
            "name":"Crew S32 Set",
            "description":"",
            "effect":[{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":140,
               "chance":0
            }],
            "member_list":["back735","back736","wpn1597","wpn1598","wpn1599","wpn1600","wpn1601"],
            "hash":"436643ff0197a5a403d4bff22b08f3976ed15cd4"
         },
         "gearset65":{
            "id":"gearset65",
            "name":"Crew S33 Set",
            "description":"Crew S33 Set",
            "effect":[{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":130,
               "chance":0
            },{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":120,
               "chance":0
            }],
            "member_list":["acsy60","back738","back739","wpn1608","wpn1609","wpn1610","wpn1611"],
            "hash":"009080b483a6e791b1154c872aa6ea4bf9e7ea10"
         },
         "gearset66":{
            "id":"gearset66",
            "name":"Janken set",
            "description":"",
            "effect":[{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":20,
               "chance":100
            }],
            "member_list":["back740","back741","back742","wpn1612","wpn1613","wpn1614"],
            "hash":"03d197ddab997b2cf356256f437042fc066b1314"
         },
         "gearset67":{
            "id":"gearset67",
            "name":"Crew S34 Set",
            "description":"Crew S34 Set",
            "effect":[{
               "type":"add_purify_chance",
               "duration":0,
               "amount":6,
               "chance":0
            },{
               "type":"add_purify_chance",
               "duration":0,
               "amount":4,
               "chance":0
            }],
            "member_list":["acsy61","back743","back744","wpn1616","wpn1617","wpn1618","wpn1619"],
            "hash":"ada2e40e874ba0ac38bcf6958d8a9a69d9478d79"
         },
         "gearset68":{
            "id":"gearset68",
            "name":"Crew S35 Set",
            "description":"Crew S35 Set",
            "effect":[{
               "type":"attacker_critical_damage_bonus",
               "duration":0,
               "amount":14,
               "chance":100
            },{
               "type":"add_critical_chance",
               "duration":0,
               "amount":5,
               "chance":100
            }],
            "member_list":["acsy62","back745","back746","wpn1620","wpn1621","wpn1622","wpn1623"],
            "hash":"565c73312883fab49e2ef85cd48bd40c622d9f3c"
         },
         "gearset69":{
            "id":"gearset69",
            "name":"Crew S36 Set",
            "description":"Crew S36 Set",
            "effect":[{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":3,
               "chance":100
            }],
            "member_list":["acsy65","back749","back750","wpn1627","wpn1628","wpn1629","wpn1630"],
            "hash":"978bad0055fdd9f6383e9e5cc87fa4612480bd11"
         },
         "gearset70":{
            "id":"gearset70",
            "name":"Crew S37 Set",
            "description":"Crew S37 Set",
            "effect":[{
               "type":"add_dodge_random",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"add_dodge_random",
               "duration":0,
               "amount":4,
               "chance":100
            }],
            "member_list":["acsy66","back751","back752","wpn1631","wpn1632","wpn1633","wpn1634"],
            "hash":"a0267b75bc7d8da471f7589348ece2463b1d03b6"
         },
         "gearset71":{
            "id":"gearset71",
            "name":"Crew S38 Set",
            "description":"Crew S38 Set",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":9,
               "chance":100
            },{
               "type":"add_critical_chance",
               "duration":0,
               "amount":10,
               "chance":100
            }],
            "member_list":["acsy67","back759","back760","wpn1642","wpn1643","wpn1644","wpn1645"],
            "hash":"fe677923654f333abd428f2f70860473b04bef6b"
         },
         "gearset72":{
            "id":"gearset72",
            "name":"Crew S39 Set",
            "description":"",
            "effect":[{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":5,
               "chance":100
            },{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":7,
               "chance":100
            }],
            "member_list":["acsy69","back765","back766","wpn1650","wpn1651","wpn1652","wpn1653"],
            "hash":"c02f6c800bce172714d0863dd06d4525fef87faa"
         },
         "gearset73":{
            "id":"gearset73",
            "name":"Crew S40 Set",
            "description":"Crew S40 Set",
            "effect":[{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":5,
               "chance":100
            },{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":5,
               "chance":100
            }],
            "member_list":["acsy70","back767","back768","wpn1654","wpn1655","wpn1656","wpn1657"],
            "hash":"f62676f0b59df00dccc12895400754ac2d739e76"
         },
         "gearset74":{
            "id":"gearset74",
            "name":"Crew S41 Set",
            "description":"Crew S41 Set",
            "effect":[{
               "type":"reduce_hp_present",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"reduce_hp_present",
               "duration":0,
               "amount":3,
               "chance":100
            }],
            "member_list":["acsy72","back773","back774","wpn1661","wpn1662","wpn1663","wpn1664"],
            "hash":"a9c54d325f4081c00ce6d893226a6a51c64115ad"
         },
         "gearset75":{
            "id":"gearset75",
            "name":"Crew S42 Set",
            "description":"Crew S42 Set",
            "effect":[{
               "type":"reduce_hp_present",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"reduce_hp_present",
               "duration":0,
               "amount":3,
               "chance":100
            }],
            "member_list":["acsy73","back776","back777","wpn1665","wpn1666","wpn1667","wpn1668"],
            "hash":"cf45fffcedca04c124c330c4c6657578c3f8bc9a"
         },
         "gearset76":{
            "id":"gearset76",
            "name":"Crew S43 Set",
            "description":"Crew S43 Set",
            "effect":[{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":7,
               "chance":100
            },{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":10,
               "chance":100
            }],
            "member_list":["acsy78","back784","back785","wpn1678","wpn1679","wpn1680","wpn1681"],
            "hash":"65be5c8f0050a95be622e15cbd065ce79bbd61ea"
         },
         "gearset77":{
            "id":"gearset77",
            "name":"Crew S44 Set",
            "description":"Crew S44 Set",
            "effect":[{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":6,
               "chance":100
            },{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["acsy79","back786","back787","wpn1682","wpn1683","wpn1684","wpn1685"],
            "hash":"9719700efaa115ea13f8c1ae7ed09c97a9b0a030"
         },
         "gearset78":{
            "id":"gearset78",
            "name":"Crew S45 Set",
            "description":"",
            "effect":[{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":180,
               "chance":100
            },{
               "type":"reduce_damage_bonus",
               "duration":0,
               "amount":190,
               "chance":100
            }],
            "member_list":["acsy81","back788","back789","wpn1686","wpn1687","wpn1688","wpn1689"],
            "hash":"462d324fddc7f71d300890990d47901fe8dbd911"
         },
         "gearset79":{
            "id":"gearset79",
            "name":"Crew S46 Set",
            "description":"",
            "effect":[{
               "type":"add_dodge_random",
               "duration":0,
               "amount":3,
               "chance":100
            },{
               "type":"add_dodge_random",
               "duration":0,
               "amount":6,
               "chance":100
            }],
            "member_list":["acsy94","back792","back793","wpn1690","wpn1691","wpn1692","wpn1693"],
            "hash":"5400e6c6247efed42f2017055799da8df1077731"
         },
         "gearset80":{
            "id":"gearset80",
            "name":"Crew S47 Set",
            "description":"Crew S47 Set",
            "effect":[{
               "type":"reduce_hp_present",
               "duration":0,
               "amount":4,
               "chance":100
            },{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":7,
               "chance":100
            }],
            "member_list":["acsy98","back796","back797","wpn1699","wpn1700","wpn1701","wpn1702"],
            "hash":"1766d822c815464e0a76df26ef58299f1f198565"
         },
         "gearset81":{
            "id":"gearset81",
            "name":"Crew S48 Set",
            "description":"",
            "effect":[{
               "type":"add_hp_amount",
               "duration":0,
               "amount":180,
               "chance":100
            },{
               "type":"add_hp_amount",
               "duration":0,
               "amount":220,
               "chance":100
            }],
            "member_list":["acsy103","back815","back816","wpn1725","wpn1726","wpn1727","wpn1728"],
            "hash":"12d100e9bf1ea3a40af36c70d8dd204dbba05227"
         },
         "gearset82":{
            "id":"gearset82",
            "name":"S49 Crew",
            "description":"",
            "effect":[{
               "type":"reduce_damage_amount",
               "duration":0,
               "amount":7,
               "chance":100
            },{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":180,
               "chance":100
            }],
            "member_list":["acsy103","back815","back816","wpn1725","wpn1726","wpn1727","wpn1728"],
            "hash":"6c7e90e1f975e317702c39c18353194094b4d926"
         },
         "gearset83":{
            "id":"gearset83",
            "name":"S50 Crew",
            "description":"S50 Crew",
            "effect":[{
               "type":"add_purify_chance",
               "duration":0,
               "amount":6,
               "chance":0
            },{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":5,
               "chance":100
            }],
            "member_list":["acsy104","back817","back818","wpn1729","wpn1730","wpn1731","wpn1732"],
            "hash":"068cc84faf186ce1b5265c24a175312905632b13"
         },
         "gearset84":{
            "id":"gearset84",
            "name":"Crew S51 Set",
            "description":"",
            "effect":[{
               "type":"add_cp_amount_present",
               "duration":0,
               "amount":7,
               "chance":100
            },{
               "type":"add_dodge_reduction",
               "duration":0,
               "amount":12,
               "chance":100
            }],
            "member_list":["acsy105","back819","back820","wpn1733","wpn1734","wpn1735","wpn1736"],
            "hash":"e3e48296c79d17f90ba18bea38f55c2462703af0"
         },
         "gearset85":{
            "id":"gearset85",
            "name":"Crew S52 Set",
            "description":"Crew S52 Set",
            "effect":[{
               "type":"add_hp_amount_present",
               "duration":0,
               "amount":7,
               "chance":100
            },{
               "type":"reduce_damage_bonus",
               "duration":0,
               "amount":200,
               "chance":100
            }],
            "member_list":["acsy106","back821","back822","wpn1737","wpn1738","wpn1739","wpn1740"],
            "hash":"3f190ab9614b93f91248c37f81f72a747a992138"
         },
         "gearset86":{
            "id":"gearset86",
            "name":"Crew S53 Set",
            "description":"Crew S53 Set",
            "effect":[{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":180,
               "chance":100
            },{
               "type":"effect_max_hp_present",
               "duration":0,
               "amount":7,
               "chance":100
            }],
            "member_list":["acsy107","back827","back828","wpn1745","wpn1746","wpn1747","wpn1748"],
            "hash":"dbfd3eb1d667ac5fdf26752d30fe5a9696d05d62"
         },
         "gearset87":{
            "id":"gearset87",
            "name":"Crew S54 Set",
            "description":"Crew S53 Set",
            "effect":[{
               "type":"add_damage_bonus",
               "duration":0,
               "amount":6,
               "chance":100
            },{
               "type":"dmgbonus_fix_num",
               "duration":0,
               "amount":185,
               "chance":100
            }],
            "member_list":["acsy109","back834","back835","wpn1753","wpn1754","wpn1755","wpn1756"],
            "hash":"a583e662c77d12a65ff66054d435f47477fa8653"
         }
      };

const GEAR_SET_TEXT = {
	"defender_poison":"Poisons the target by [amount]% for [duration] turns",
	"pet_weaken_fix_num":"Weaken enemy upon each weapon attack - reduce [amount] HP damage for [duration] turns",
	"add_hp_amount_present":"Recover HP by [amount]% every turn",
	"add_hp_amount":"Recovers [amount] HP every turn",
	"add_damage_bonus":"Increase all attack damage by [amount]%",
	"add_dodge_reduction":"Increase [amount]% accuracy",
	"attacker_damage_bonus":"Increases attack damage by [amount]% until the end of next turn after using the weapon",
	"add_critical_chance":"Increase critical chance by [amount]%",
	"reduce_damage_amount":"Decrease damage taken by [amount]%",
	"add_cp_amount_present":"Recover CP by [amount]% every turn",
	"absorb_attacker_hp_present":"Has [chance]% chance to absorb [amount]% HP of enemy who attack you",
	"xp_bouns":"Increase mission XP reward by [amount]",
	"add_purify_chance":"Increase purify chance every turn by [amount]%",
	"effect_agility":"Increases agility by [amount]",
	"effect_max_cp_present":"Increase max. CP by [amount]%",
	"recieve_damage_cp":"Recover CP after HP reduction. (Amount: [amount]% of HP reduction)",
	"reduce_damage_bonus":"Reduce damage taken by [amount]",
	"add_cp_amount":"Recover [amount] CP at the start of every turn",
	"add_dodge_random":"Increases dodge chance by [amount]%",
	"effect_max_hp_present":"Increase max. HP by [amount]%",
	"dmgbonus_fix_num":"Additional[amount]HP damage upon all attack.",
	"attacker_critical_damage_bonus":"Increase critical damage[amount]%",
	"add_sp_amount_present":"Recover [amount]% SP at the start of every turn.",
	"reduce_hp_present":"[chance]% chance to reduce enemy\'s [amount]% HP upon each attack.",
};

const EXTRA_EFFECT_TEXT = {
         "burn_cp":"Reduce target [enemy][amount]% CP on every damage attack",
         "clear_bless_n_reduce_hp":"[enemy]\'s positive status \"Bless\" effect will be removed when hit and reduce [amount]% HP",
         "burn_hp":" Reduce target [enemy][amount]% HP on every damage attack   ",
         "item_reduce_target_hp":"Reduce target\'s maximum HP by [amount]%",
         "clearbuff_stun":"Removes all positive status of the target and stun target for 3 turn.",
         "reduce_purify_n_dodge":"Reduces target\'s purify chance and dodge rate by [amount]% for 10 turns.",
         "reduce_damage_bonus_present":" Reduce damage from [enemy] by [amount]%",
         "clear_bless_n_reduce_hp":"Invalid [enemy]\'s positive status \"Bless\" effect when hit and reduce [amount]% HP"
}